import { encodeBase64String } from "@temelj/string";
import { isPlainObject } from "@temelj/value";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

class EntityGenerationError extends Error {
  public static downloadFailed(url: string, status: number): never {
    throw new EntityGenerationError(`Could not download ${url}: ${status}`);
  }

  public static invalidExport(): never {
    throw new EntityGenerationError("character-entities did not export a record");
  }

  public static invalidEntry(): never {
    throw new EntityGenerationError("character-entities exported an invalid entry");
  }

  private constructor(message: string) {
    super(message);
    this.name = "EntityGenerationError";
  }
}

async function fetchSource(url: string): Promise<string> {
  const response = await fetch(url);
  if (!response.ok) {
    EntityGenerationError.downloadFailed(url, response.status);
  }
  return response.text();
}

function readCharacterEntities(value: unknown): Record<string, string> {
  if (!isPlainObject(value)) {
    EntityGenerationError.invalidExport();
  }
  const entities: Record<string, string> = {};
  for (const [name, replacement] of Object.entries(value)) {
    if (name.length === 0 || typeof replacement !== "string") {
      EntityGenerationError.invalidEntry();
    }
    entities[name] = replacement;
  }
  return entities;
}

async function main() {
  const characterEntitiesVersion = "2.0.2";
  const sourceUrl = `https://cdn.jsdelivr.net/npm/character-entities@${characterEntitiesVersion}/index.js`;
  const packageDirectory = resolve(dirname(fileURLToPath(import.meta.url)), "..");
  const destination = resolve(packageDirectory, "src/syntax/generated/character-entities.ts");
  const source =
    process.argv[2] === undefined
      ? await fetchSource(sourceUrl)
      : await readFile(resolve(process.cwd(), process.argv[2]), "utf8");
  const encoded = encodeBase64String(source);
  const imported = await import(`data:text/javascript;base64,${encoded}`);
  const entities = readCharacterEntities(imported.characterEntities);
  const ordered = Object.fromEntries(
    Object.entries(entities).sort(([left], [right]) => (left < right ? -1 : left > right ? 1 : 0)),
  );
  const output = `// Generated by scripts/generate-character-entities.ts from character-entities@${characterEntitiesVersion}.\n// Do not edit by hand.\n\nexport const namedCharacterReferences: Readonly<Record<string, string>> = Object.freeze(${JSON.stringify(ordered, undefined, 2)});\n`;

  await mkdir(dirname(destination), { recursive: true });
  await writeFile(destination, output);
}

void main();
