import { z } from "zod";

/** Stable machine-readable conditions emitted by the workflow package. */
export const WorkflowErrorCode = {
  ERROR: "workflow.error",
  DEFINITION_INVALID: "definition.invalid",
  CAPABILITY_UNSUPPORTED: "capability.unsupported",
  OPTIONS_INVALID: "options.invalid",
  OPTIONS_EXPECTED_OBJECT: "options.expected_object",
  OPTIONS_EXPECTED_ARRAY: "options.expected_array",
  OPTIONS_EXPECTED_FUNCTION: "options.expected_function",
  OPTIONS_EXPECTED_STRING: "options.expected_string",
  OPTIONS_EXPECTED_NON_EMPTY: "options.expected_non_empty",
  OPTIONS_EXPECTED_NON_BLANK: "options.expected_non_blank",
  OPTIONS_EXPECTED_NUMBER: "options.expected_number",
  OPTIONS_EXPECTED_BOOLEAN: "options.expected_boolean",
  OPTIONS_REQUIRED: "options.required",
  OPTIONS_EXPECTED_POSITIVE_SAFE_INTEGER: "options.expected_positive_safe_integer",
  OPTIONS_EXPECTED_NON_NEGATIVE_SAFE_INTEGER: "options.expected_non_negative_safe_integer",
  OPTIONS_EXPECTED_POSITIVE_DURATION: "options.expected_positive_duration",
  OPTIONS_EXPECTED_NON_NEGATIVE_DURATION: "options.expected_non_negative_duration",
  OPTIONS_EXPECTED_TIMER_SAFE_DURATION: "options.expected_timer_safe_duration",
  OPTIONS_EXPECTED_POSITIVE_SAFE_INTEGER_DURATION:
    "options.expected_positive_safe_integer_duration",
  OPTIONS_EXPECTED_TEMPORAL_INSTANT: "options.expected_temporal_instant",
  OPTIONS_EXPECTED_ABORT_SIGNAL: "options.expected_abort_signal",
  OPTIONS_CHILD_CANCELLATION_POLICY_INVALID: "options.child_cancellation_policy_invalid",
  OPTIONS_CURSOR_INVALID: "options.cursor_invalid",
  OPTIONS_RETRY_MAXIMUM_INTERVAL_TOO_SMALL: "options.retry_maximum_interval_too_small",
  OPTIONS_RETRYABLE_ERROR_DELAY_CONFLICT: "options.retryable_error_delay_conflict",
  OPTIONS_ENGINE_STORE_STORAGE_CONFLICT: "options.engine_store_storage_conflict",
  OPTIONS_MISSING_IMPLEMENTATION_RETRY_ATTEMPT_INVALID:
    "options.missing_implementation_retry_attempt_invalid",
  STATE_INVALID: "state.invalid",
  STATE_RUN_NAMESPACE_MISMATCH: "state.run_namespace_mismatch",
  STATE_RUN_ID_MISMATCH: "state.run_id_mismatch",
  STATE_RUN_ALREADY_EXISTS: "state.run_already_exists",
  STATE_EVENT_HISTORY_ALREADY_EXISTS: "state.event_history_already_exists",
  STATE_EVENT_NOT_TERMINAL_STEP: "state.event_not_terminal_step",
  STATE_RECORDED_STEP_EVENT_UNSUPPORTED: "state.recorded_step_event_unsupported",
  STATE_STEP_ATTEMPT_FIELD_MISMATCH: "state.step_attempt_field_mismatch",
  STATE_FAILED_RUN_MISSING_ERROR: "state.failed_run_missing_error",
  STATE_RUN_NOT_CLAIMABLE: "state.run_not_claimable",
  STATE_WORKER_STOPPED_BEFORE_RUN: "state.worker_stopped_before_run",
  STATE_STORE_RUN_ID_INVALID: "state.store_run_id_invalid",
  STATE_IDEMPOTENCY_KEY_CLAIMED_WITHOUT_RUN: "state.idempotency_key_claimed_without_run",
  STATE_RUN_MISSING_IDEMPOTENCY_KEY: "state.run_missing_idempotency_key",
  STATE_RUN_METADATA_UPDATE_FAILED: "state.run_metadata_update_failed",
  STATE_RUN_ATTRIBUTES_UPDATE_FAILED: "state.run_attributes_update_failed",
  STATE_RUN_CANNOT_BE_RESCHEDULED: "state.run_cannot_be_rescheduled",
  STATE_RUN_RESCHEDULE_FAILED: "state.run_reschedule_failed",
  STATE_STALE_LEASE_RELEASE_REQUIRES_RUNNING: "state.stale_lease_release_requires_running",
  STATE_RUN_LEASE_STILL_ACTIVE: "state.run_lease_still_active",
  STATE_STALE_RUN_LEASE_RELEASE_FAILED: "state.stale_run_lease_release_failed",
  STATE_RUN_RETRY_REQUIRES_FAILED: "state.run_retry_requires_failed",
  STATE_RUN_RETRY_REQUIRES_FORCE_AFTER_PERMANENT_FAILURE:
    "state.run_retry_requires_force_after_permanent_failure",
  STATE_FAILED_RUN_RETRY_REQUIRES_FORCE: "state.failed_run_retry_requires_force",
  STATE_RUN_RETRY_FAILED: "state.run_retry_failed",
  STATE_PERMANENT_RUN_FAILURE_FAILED: "state.permanent_run_failure_failed",
  STATE_PERMANENT_FAILURE_STATUS_INVALID: "state.permanent_failure_status_invalid",
  STATE_MESSAGE_APPEND_FAILED: "state.message_append_failed",
  STATE_CLEANUP_SELECTED_NON_TERMINAL_RUN: "state.cleanup_selected_non_terminal_run",
  STATE_CLEANUP_RUN_MISSING_FINISHED_AT: "state.cleanup_run_missing_finished_at",
  STATE_WORKFLOW_EVENT_APPEND_FAILED: "state.workflow_event_append_failed",
  STATE_STEP_ATTEMPT_MATERIALIZATION_FAILED: "state.step_attempt_materialization_failed",
  STATE_APPEND_PROJECTION_PIPELINE_MISSING: "state.append_projection_pipeline_missing",
  RUNTIME_INVALID: "runtime.invalid",
  RUN_ERROR: "run.error",
  STEP_ERROR: "step.error",
  MESSAGE_ERROR: "message.error",
  IMPLEMENTATION_NOT_FOUND: "implementation.not_found",
  DURATION_INVALID: "duration.invalid",
  SERIALIZATION_FAILED: "serialization.failed",
  NON_RETRYABLE_FAILURE: "failure.non_retryable",
  PERMANENT_FAILURE: "failure.permanent",
  RETRYABLE_FAILURE: "failure.retryable",
  REPLAY_DIVERGED: "replay.diverged",
  LOCK_ALREADY_HELD: "lock.already_held",
  RUN_NOT_FOUND: "run.not_found",
  RUN_INVALID: "run.invalid",
  RUN_WORKFLOW_MISMATCH: "run.workflow_mismatch",
  RUN_RESULT_TIMEOUT: "run.result_timeout",
  RUN_CANCELED: "run.canceled",
  RUN_CANCELLATION_REJECTED: "run.cancellation_rejected",
  RUN_TRANSITION_INVALID: "run.transition_invalid",
  RUN_PARENT_INVALID: "run.parent_invalid",
  RUN_DEADLINE_EXCEEDED: "run.deadline_exceeded",
  CHILD_WORKFLOW_TIMEOUT: "child_workflow.timeout",
  MESSAGE_WAIT_TIMEOUT: "message.wait_timeout",
  HOOK_DISPOSED: "hook.disposed",
  MESSAGE_DELIVERY_REJECTED: "message.delivery_rejected",
  MESSAGE_IDEMPOTENCY_CONFLICT: "message.idempotency_conflict",
  STEP_TIMEOUT: "step.timeout",
  STEP_EXECUTION_FAILED: "step.execution_failed",
  STEP_RETRY_LIMIT_EXCEEDED: "step.retry_limit_exceeded",
  STEP_ATTEMPT_LIMIT_EXCEEDED: "step.attempt_limit_exceeded",
  SCHEDULE_ALREADY_EXISTS: "schedule.already_exists",
  SCHEDULE_NAMESPACE_MISMATCH: "schedule.namespace_mismatch",
  SCHEDULE_RECORD_INVALID: "schedule.record_invalid",
  SCHEDULE_ID_CHANGE_REJECTED: "schedule.id_change_rejected",
  SCHEDULE_CURRENT_RECORD_INVALID: "schedule.current_record_invalid",
  SCHEDULE_NEXT_RECORD_INVALID: "schedule.next_record_invalid",
  SCHEDULE_UPSERT_CONFLICT_EXHAUSTED: "schedule.upsert_conflict_exhausted",
  SCHEDULE_NOT_FOUND: "schedule.not_found",
  SCHEDULE_UPDATE_CONFLICT_EXHAUSTED: "schedule.update_conflict_exhausted",
  STREAM_NOT_FOUND: "stream.not_found",
  STREAM_CHUNK_LIMIT_EXCEEDED: "stream.chunk_limit_exceeded",
  STREAM_READ_OFFSET_CONFLICT: "stream.read_offset_conflict",
  STREAM_CHUNK_INDEX_NON_CONTIGUOUS: "stream.chunk_index_non_contiguous",
  STREAM_CHUNK_AFTER_TERMINAL: "stream.chunk_after_terminal",
  STREAM_ALREADY_CLOSED: "stream.already_closed",
  LOCK_ALREADY_HELD_WITHOUT_WAIT: "lock.already_held_without_wait",
  LOCK_HOLDER_MISMATCH: "lock.holder_mismatch",
  LOCK_ALREADY_RELEASED: "lock.already_released",
  LOCK_NOT_STALE: "lock.not_stale",
  LOCK_WAIT_DEADLINE_CONFLICT: "lock.wait_deadline_conflict",
  LOCK_TIMEOUT_REQUIRES_WAIT: "lock.timeout_requires_wait",
  LOCK_NAMESPACE_MISMATCH: "lock.namespace_mismatch",
  LOCK_KEY_CHANGE_REJECTED: "lock.key_change_rejected",
  LOCK_CURRENT_RECORD_INVALID: "lock.current_record_invalid",
  LOCK_NEXT_RECORD_INVALID: "lock.next_record_invalid",
  LOCK_ACQUIRE_CONFLICT_EXHAUSTED: "lock.acquire_conflict_exhausted",
  LOCK_NOT_FOUND: "lock.not_found",
  LOCK_RELEASE_CONFLICT_EXHAUSTED: "lock.release_conflict_exhausted",
  LOCK_STALE_RELEASE_CONFLICT_EXHAUSTED: "lock.stale_release_conflict_exhausted",
  HOOK_TOKEN_INVALID: "hook.token_invalid",
  WEBHOOK_TOKEN_INVALID: "webhook.token_invalid",
  HOOK_TOKEN_NOT_UNIQUE: "hook.token_not_unique",
  HOOK_WAITING_STEP_MISSING: "hook.waiting_step_missing",
} as const;

export const workflowErrorCodeSchema = z.enum(WorkflowErrorCode);
export type WorkflowErrorCode = z.infer<typeof workflowErrorCodeSchema>;
